### ISSUE TITLE
Note

### ISSUE THREAD

**Issue by kimocoder** [kimocoder/qualcomm_android_monitor_mode#2]
Well @ZerBea ... This one's a happy go lucky find!
  All QCACLD WiFi drivers (Android) supports monitor mode on the internal :1st_place_medal:

**Comment by ZerBea** [comment]
The sounds good. Thanks for that important information.
How about the active part (full packet injection inclusive short packets like ack).

**Comment by AlmondWhite** [comment]
Amazing. So a default NetHunter on a QCACLD supported device, like the Mi 9T from your ReadMe will support monitor mode by default now? Without a patch?

**Comment by AlmondWhite** [comment]
Answering my own question, and yours, a little more:

https://www.kali.org/news/kali-nethunter-updates/#user-content-monitor-mode-for-internal-qcacld-wlan0-chips
