### ISSUE TITLE
NULL PWR LVL

### ISSUE THREAD

**Issue by Geofferey** [kimocoder/qualcomm_android_monitor_mode#20]
Hi, I just discovered monitor mode on my Oneplus7T thanks to the information you provided in this repo. I was wondering if I should expect power levels to be -1/-95 in airodump or maybe I am just missing something? I am using my own home built NH kernel. Do you think this would require patching of the QCACLD driver?

**Comment by kimocoder** [comment]
Import latest linux-stable & latest CAF tags for QCACLD-3.

**Comment by Geofferey** [comment]
I see.... 

https://source.codeaurora.org/quic/la/platform/vendor/qcom-opensource/wlan/qcacld-3.0/commit/?h=wlan-cld3.driver.lnx.2.0.3.r13-rel&id=898455cec598eea0b7c3fe5fea82c2270a34b49e

Wonder if I can get some of this stuff in without fully updating everything. There would be a lot of issues, I imagine with merging everything in & my limited experience.
