### ISSUE TITLE
patch for bcmdhd 

### ISSUE THREAD

**Issue by SamuelNigga** [kimocoder/qualcomm_android_monitor_mode#7]
hi dear @kimocoder 
my device uses bcm43455, kernel source: 
https://github.com/LineageOS/android_kernel_sony_msm8994

i think your patch doesnt works for my device because there isnt /drivers/staging/qcacld-3.0/configs/default_defconfig file in my device's source.

but @ruleh writed patch for bcmdhd: https://github.com/ruleh/misc/blob/master/monitor/bcmdhd_enable_monitor.patch

can this work for my device ?
regards..

**Comment by kimocoder** [comment]
Broadcom and Qualcomm is 2 different chipset manufacturers.

**Comment by SamuelNigga** [comment]
> Broadcom and Qualcomm is 2 different chipset manufacturers.

sir so if i apply bcm patch in my kernel source and compile it, then flash compiled image, native monitor mode can work ?

**Comment by kimocoder** [comment]
I don't know about the bcmdhd driver, haven't been looking into that one (bcmon scripts) etc in years, however it doesn't have anything to do with the QCACLD WiFi SoC
